GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhYnJAZ21haWwuY29tIiwiaWF0IjoxNzQ2NzcyMDYzLCJleHAiOjE3NDY3NzIwOTN9.jkilmyrA9ogU0wPRMNDrpVjb39HAfHTdEn3QKPWQq5U

###
GET http://localhost:5000/users

###
GET http://localhost:5000/songs

###
GET http://localhost:5000/songs/3

###
PUT http://localhost:5000/edit-song/3
Content-Type: application/json
{
    "artist": "Boldenn"
}

###
POST http://localhost:5000/register
Content-Type: application/json
{
    "email": "flcia@tes.com",
    "password": "12345"
}

### 
PUT http://localhost:5000/edit-user/7
Content-Type: application/json
{
    "email": "arf@gmail.com"
}

###
DELETE http://localhost:5000/delete-song/15


###
GET http://localhost:5000/playlist

###
GET http://localhost:5000/playlist/1

###
GET http://localhost:5000/playlist-with-songs/2


###
POST http://localhost:5000/login

Content-Type: application/json
{
    "email": "fzz@gmail.com",
    "password": "12345"
}



###
DELETE http://localhost:5000/logout

