@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJmdHJobW5AZ21haWwuY29tIiwiaWF0IjoxNzQ3MTU3OTg1LCJleHAiOjE3NDcxNTgyODV9.DHe4EzzRSoFP7d9YqXctgU1xfaBDxOcuJYeieWSu580

GET http://localhost:5000/users
Authorization: Bearer {{token}}


###
GET http://localhost:5000/users/4
Authorization: Bearer {{token}}



###

POST http://localhost:5000/register
Authorization: Bearer {{token}}

{
    "email": "ftrhmn@gmail.com",
    "password": "12345"
}

### 
PUT http://localhost:5000/edit-user/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "fatur@gmail.com",
    "password": "12345"
}

###

DELETE http://localhost:5000/delete-user/2
Authorization: Bearer {{token}}

###

POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "ftrhmn@gmail.com",
    "password": "12345"
}



###

DELETE http://localhost:5000/logout
Authorization: Bearer {{token}}