GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhYnJAZ21haWwuY29tIiwiaWF0IjoxNzQ2NzcyMDYzLCJleHAiOjE3NDY3NzIwOTN9.jkilmyrA9ogU0wPRMNDrpVjb39HAfHTdEn3QKPWQq5U
###

GET http://localhost:5000/users


###

POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "tes@tes.com",
    "password": "12345",
    "refresh_token": ""
}

### 
PUT http://localhost:5000/edit-user/7
Content-Type: application/json

{
    "email": "arf@gmail.com"
}

###

DELETE http://localhost:5000/delete-user/1


###

POST http://localhost:5000/login
Content-Type: application/json

{
   
    "email": "fzz@gmail.com",
    "password": "12345"
}



###

DELETE http://localhost:5000/logout